#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A config inspect ping
}

until worker_ready; do
    echo >&2 "Celery workers are not available :-("
    sleep 1
done
echo >&2 "Celery workers are available and ready!....:-)"

celery -A config \
    --broker="${CELERY_BROKER}" \
    flower \
    --basic_auth="${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
